---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  TableName:
    Type: String

Resources:
  UserTable:
    Type: AWS::DynamoDB::Table
    Description: Holds user information
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "N"
        - AttributeName: "name"
          AttributeType: "S"
        - AttributeName: "country"
          AttributeType: "S"
        - AttributeName: "gender"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
        - AttributeName: "name"
          KeyType: "RANGE"
      GlobalSecondaryIndexes:
        - IndexName: "GenderGSI"
          KeySchema:
            - AttributeName: "gender"
              KeyType: "HASH"
            - AttributeName: "country"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: Purpose
          Value: User Info Table
